import { ElementRef, OnDestroy, EventEmitter, OnChanges, SimpleChanges, OnInit, QueryList, AfterContentInit } from '@angular/core';
import { Router } from '@angular/router';
import { MotionOneService } from '../services/motion-one.service';
import { MotionAnimationService } from '../services/motion-animation.service';
import * as i0 from "@angular/core";
export interface TransitionOptions {
    duration?: number;
    delay?: number;
    ease?: string | number[] | {
        type: 'spring';
        stiffness?: number;
        damping?: number;
    };
    repeat?: number | boolean;
    repeatType?: 'loop' | 'mirror' | 'reverse' | 'forwards' | 'pingPong';
    repeatDelay?: number;
    staggerChildren?: number;
    staggerDirection?: number;
    when?: 'beforeChildren' | 'afterChildren' | 'together';
    delayChildren?: number;
    times?: number[];
}
export interface VariantWithTransition {
    [key: string]: any;
    transition?: TransitionOptions;
    at?: number;
}
export interface TimelineStep {
    prop: string;
    keyframes?: any[] | any;
    to?: any;
    duration: number;
    delay?: number;
    ease?: string | number[] | {
        type: 'spring';
        stiffness?: number;
        damping?: number;
    };
    atTime?: number;
    times?: number[];
    repeat?: number | boolean;
    repeatType?: 'loop' | 'mirror' | 'reverse' | 'forwards' | 'pingPong';
    repeatDelay?: number;
}
export declare class MotionOneDirective implements OnInit, OnDestroy, OnChanges, AfterContentInit {
    el: ElementRef;
    private motionService;
    private motionAnimation;
    private router;
    private platformId;
    initial: VariantWithTransition | string;
    animate: VariantWithTransition | string;
    exit: VariantWithTransition | string;
    inView: VariantWithTransition;
    duration: number;
    delay: number;
    delayChildren: number;
    repeat: boolean;
    exitDelay: number;
    easing: string | number[] | {
        type: 'spring';
        stiffness?: number;
        damping?: number;
    };
    offset: string;
    whileHover: VariantWithTransition;
    staggerChildren: number;
    staggerDirection: number;
    whileTap: VariantWithTransition;
    whileFocus: VariantWithTransition;
    whileInView: VariantWithTransition;
    runInView?: 'never' | 'once' | 'always';
    variants: {
        [key: string]: VariantWithTransition;
    };
    transition: TransitionOptions | Record<string, TransitionOptions>;
    timeline: TimelineStep[] | undefined;
    animationComplete: EventEmitter<void>;
    restartAnimation(): void;
    childMotionDirectives: QueryList<MotionOneDirective>;
    private controls;
    private childrenControls;
    elementId: string;
    private hoverTimeout;
    private observer?;
    private routeDelay;
    private inViewInstance;
    private isChild;
    private parentDirective;
    private initialAnimationPlayed;
    private _skipStartStylesApplication;
    private staggerDelay;
    private childrenCount;
    private childIndex;
    private isStaggeredChild;
    get scrollProgress(): number;
    private get isRunInViewEnabled();
    private get runInViewRepeat();
    constructor(el: ElementRef, motionService: MotionOneService, motionAnimation: MotionAnimationService, router: Router, platformId: Object);
    ngOnInit(): void;
    ngAfterContentInit(): void;
    setParent(parent: MotionOneDirective, index: number, totalChildren: number): void;
    completeResetToInitial(): void;
    forceResetToInitial(): void;
    resetToInitialIfParentHasRunInView(): void;
    parentExitViewportReset(): void;
    private setupRunInViewObserver;
    private handleViewportEntry;
    private handleViewportExit;
    applyStaggerToChildren(): void;
    overrideDelay(delay: number): void;
    runSelfAnimation(): void;
    ngOnDestroy(): void;
    ngOnChanges(changes: SimpleChanges): void;
    onMouseEnter(): void;
    onMouseLeave(): void;
    onPress(event: Event): void;
    onFocus(): void;
    onBlur(): void;
    applyInitialValues(): void;
    private applyInitialStyles;
    private applyAnimateStyles;
    extractStyleProperties(variant: VariantWithTransition): Record<string, any>;
    private isTransformProperty;
    private applyTransformProperty;
    private multiplyMatrices;
    private applyStyleProperty;
    private isColorProperty;
    private normalizeTransformProperty;
    private getEasing;
    private getAnimationOptions;
    private getRepeatValue;
    private mapRepeatTypeToDirection;
    private getStaggerValue;
    private getStaggerDirection;
    private getWhen;
    private playAnimation;
    private continueAnimation;
    private runPerPropertyAnimations;
    private runTimeline;
    private setupInViewAnimation;
    runInViewAnimation(): void;
    private setupWhileInViewAnimation;
    private setupMotionOneInView;
    private setupStaggerParentInView;
    private setupIndividualElementInView;
    runInitAnimation(): void;
    runExitAnimation(): Promise<void>;
    cancel(): void;
    getDuration(): number;
    getKeyByValue(object: any, key: any): string | undefined;
    private logDebug;
    private normalizeColor;
    private normalizeTimes;
    triggerExitAnimation(): Promise<void>;
    onMotionExit(): void;
    getVariant(variant: VariantWithTransition | string): VariantWithTransition;
    static ɵfac: i0.ɵɵFactoryDeclaration<MotionOneDirective, never>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<MotionOneDirective, "[motionone]", ["motionone"], { "initial": { "alias": "initial"; "required": false; }; "animate": { "alias": "animate"; "required": false; }; "exit": { "alias": "exit"; "required": false; }; "inView": { "alias": "inView"; "required": false; }; "duration": { "alias": "duration"; "required": false; }; "delay": { "alias": "delay"; "required": false; }; "delayChildren": { "alias": "delayChildren"; "required": false; }; "repeat": { "alias": "repeat"; "required": false; }; "exitDelay": { "alias": "exitDelay"; "required": false; }; "easing": { "alias": "easing"; "required": false; }; "offset": { "alias": "offset"; "required": false; }; "whileHover": { "alias": "whileHover"; "required": false; }; "staggerChildren": { "alias": "staggerChildren"; "required": false; }; "staggerDirection": { "alias": "staggerDirection"; "required": false; }; "whileTap": { "alias": "whileTap"; "required": false; }; "whileFocus": { "alias": "whileFocus"; "required": false; }; "whileInView": { "alias": "whileInView"; "required": false; }; "runInView": { "alias": "runInView"; "required": false; }; "variants": { "alias": "variants"; "required": false; }; "transition": { "alias": "transition"; "required": false; }; "timeline": { "alias": "timeline"; "required": false; }; }, { "animationComplete": "animationComplete"; }, ["childMotionDirectives"], never, true, never>;
}
